version: "3"
services:
  attu:
    command:
      - '/bin/bash -c /app/build/env.sh && yarn start:prod'
    container_name: attu
    entrypoint:
      - docker-entrypoint.sh
    environment:
      - Milvus_docker=19530
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NODE_VERSION=22.21.1
      - YARN_VERSION=1.22.22
    hostname: 6db833551fbc
    image: zilliz/attu:latest
    ipc: private
    logging:
      driver: json-file
      options: {}
    mac_address: 86:be:06:5d:9f:0e
    networks:
      - bridge
    ports:
      - 8000:3000/tcp
    working_dir: /app
networks:
  bridge:
    external: true
